baseurl = "/"
languageCode = "en-us"
title = "Data Science"
theme = "hugo-theme-techdoc"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = []
math = true


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/AdnanRgithub/PessoaDataScience2"
[[menu.main]]
    name = "Lab of Cognition & Emotion"
    url = "https://LCE.umd.edu"

[params]
    description = "Overseen by Dr. Luiz Pessoa."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

